services:
  kista-ui:
    build:
      context: .
      args:
        NEXT_PUBLIC_KAKAO_CLIENT_ID: ${NEXT_PUBLIC_KAKAO_CLIENT_ID}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      API_BASE_URL: "http://host.docker.internal:8080"
    ports:
      - "3000:3000"
    restart: unless-stopped
