// entities/finance public API
export type {
  AssetClass,
  AssetSnapshot,
  AssetSnapshotRequest,
  BulkFinanceRegisterRequest,
  BulkFinanceRegisterResponse,
  FinanceAccount,
  FinanceAccountRequest,
  FinanceAccountType,
  FinanceBudget,
  FinanceBudgetRequest,
  FinanceCategory,
  FinanceCategoryRequest,
  FinanceCategoryType,
  FinanceGroup,
  FinanceGroupInvitation,
  FinanceGroupMember,
  FinanceTransaction,
  FinanceTransactionRequest,
  Market,
  MonthlyClosing,
} from './model/types'
export { financeKeys } from './model/queryKeys'
export {
  assetSnapshotListQueryOptions,
  budgetListQueryOptions,
  financeAccountListQueryOptions,
  financeCategoryListQueryOptions,
  financeGroupListQueryOptions,
  monthlyClosingListQueryOptions,
  transactionListQueryOptions,
} from './model/queryOptions'
export {
  bulkRegisterFinance,
  createAssetSnapshot,
  createFinanceAccount,
  createFinanceBudget,
  createFinanceCategory,
  createFinanceGroupInvitation,
  createFinanceTransaction,
  createSystemFinanceCategory,
  deleteAssetSnapshot,
  deleteFinanceAccount,
  deleteFinanceBudget,
  deleteFinanceCategory,
  deleteFinanceTransaction,
  deleteSystemFinanceCategory,
  listAssetSnapshots,
  listFinanceAccounts,
  listFinanceBudgets,
  listFinanceCategories,
  listFinanceGroupMembers,
  listFinanceGroups,
  listFinanceTransactions,
  listMonthlyClosings,
  listSystemFinanceCategories,
  removeFinanceGroupMember,
  respondToInvitation,
  setMonthlyClosing,
  shareAssetSnapshot,
  shareFinanceAccount,
  shareFinanceBudget,
  shareFinanceTransaction,
  unshareAssetSnapshot,
  unshareFinanceAccount,
  unshareFinanceBudget,
  unshareFinanceTransaction,
  updateAssetSnapshot,
  updateFinanceAccount,
  updateFinanceBudget,
  updateFinanceCategory,
  updateFinanceTransaction,
  updateSystemFinanceCategory,
} from './api'
export {
  useActiveGroupId,
  useAssetSnapshotsQuery,
  useCanShareToGroup,
  useFinanceAccountsQuery,
  useFinanceBudgetsQuery,
  useFinanceCategoriesQuery,
  useFinanceGroupMembersQuery,
  useFinanceGroupsQuery,
  useFinanceTransactionsQuery,
  useMonthlyClosingsQuery,
  useSetActiveGroupId,
  useSystemFinanceCategoriesQuery,
} from './hooks/useFinanceQueries'
export { useCategoryPathState } from './hooks/useCategoryPathState'
export { notifyShareCreateResult } from './lib/shareCreateToast'
export {
  useBulkRegisterFinanceMutation,
  useCreateAssetSnapshotMutation,
  useCreateFinanceAccountMutation,
  useCreateFinanceBudgetMutation,
  useCreateFinanceCategoryMutation,
  useCreateFinanceGroupInvitationMutation,
  useCreateFinanceTransactionMutation,
  useCreateSystemFinanceCategoryMutation,
  useDeleteManyAssetSnapshotsMutation,
  useDeleteFinanceAccountMutation,
  useDeleteFinanceBudgetMutation,
  useDeleteFinanceCategoryMutation,
  useDeleteFinanceTransactionMutation,
  useDeleteSystemFinanceCategoryMutation,
  useRemoveFinanceGroupMemberMutation,
  useRespondToInvitationMutation,
  useSetMonthlyClosingMutation,
  useShareAssetSnapshotMutation,
  useShareFinanceAccountMutation,
  useShareFinanceBudgetMutation,
  useShareFinanceCategoryMutation,
  useShareFinanceTransactionMutation,
  useUnshareAssetSnapshotMutation,
  useUnshareFinanceAccountMutation,
  useUnshareFinanceBudgetMutation,
  useUnshareFinanceCategoryMutation,
  useUnshareFinanceTransactionMutation,
  useUpdateAssetSnapshotMutation,
  useUpdateFinanceAccountMutation,
  useUpdateFinanceBudgetMutation,
  useUpdateFinanceCategoryMutation,
  useUpdateFinanceTransactionMutation,
  useUpdateSystemFinanceCategoryMutation,
} from './hooks/useFinanceMutations'
export type { DeleteManyAssetSnapshotsResult } from './hooks/useFinanceMutations'
export { ActiveGroupProvider } from './providers/ActiveGroupProvider'
export { assetCategoryColor, assetClassColor } from './lib/colors'
export {
  ASSET_CLASS_ORDER,
  ASSET_L1_CATEGORY_IDS,
  SYSTEM_INVESTMENT_CATEGORY_ID,
  SYSTEM_LOAN_CATEGORY_ID,
  SYSTEM_REAL_ESTATE_CATEGORY_ID,
  SYSTEM_SAVINGS_CATEGORY_ID,
  calcAssetClassBreakdown,
  calcAssetClassComposition,
  calcCategoryBreakdown,
  calcCategoryComposition,
  calcComposition,
  calcDateGroups,
  calcMissingAccounts,
  calcMissingCategories,
  calcMonthlySummary,
  calcMonthlyTrend,
  formatAssetL1CategoryLabel,
  isLiability,
  isInvestmentCategoryId,
  listAvailableMonths,
  previousMonthOf,
} from './lib/aggregate'
export type {
  AssetClassAmount,
  CategoryAmount,
  CompositionColumn,
  CompositionEntry,
  DateGroup,
  MonthlySummary,
  TrendMode,
  TrendPoint,
} from './lib/aggregate'
export { collectSubtreeIds, getCascadeLevels, getCategoryPath, sortCategoryTree } from './lib/categoryTree'
export { buildCategoryIndex, resolveCategory } from './lib/categoryIndex'
export type { CategoryIndex, CategoryIndexEntry } from './lib/categoryIndex'
export { buildBulkRegisterItems } from './lib/bulkRegisterPreview'
export type { BulkRegisterItem, BulkRegisterItems, CategoryGroupNode } from './lib/bulkRegisterPreview'
export { daysInMonth, displayWindow, elapsedDaysInMonth, elapsedMonthsInYear, isCurrentYear, monthEndDate, monthStartDate, periodRange, previousYearRange, registerWindowUpperBound, shiftMonth, windowRange, yearsRange } from './lib/period'
export type { Period, PeriodMode } from './lib/period'
export {
  calcBudgetProgress,
  calcFlowSummary,
  calcFlowTrend,
  calcUnbudgetedCategories,
  filterByType,
  unclassifiedTransactions,
} from './lib/flowAggregate'
export type { BudgetProgress, FlowSummary, FlowTrendPoint, UnbudgetedCategory } from './lib/flowAggregate'
export { flowCategoryColor } from './lib/colors'
