export type {
  StrategyTypeStats,
  StatsSummary,
  EquityPoint,
  EquityCurve,
  CyclePerformance,
  CyclePerformancePage,
  BenchmarkAssetType,
  EtfBenchmarkSymbol,
  HousingBenchmarkParams,
  CurrentExchangeRate,
  HousingBenchmarkStrategy,
  HousingBenchmark,
  HousingBenchmarkPeriod,
  HousingBenchmarkSummary,
  HousingBenchmarkPoint,
  HousingBenchmarkQuality,
  HousingBenchmarkComparison,
  HousingBenchmarkSeriesPoint,
  HousingBenchmarkSeries,
  HousingBenchmarkRegion,
  HousingBenchmarkRegionsList,
  HousingPriceIndexSeriesPoint,
  HousingPriceIndexSeries,
  EtfPriceSeriesPoint,
  EtfPriceSeries,
} from './model/types'
export { statsKeys } from './model/queryKeys'
export { statsSummaryQueryOptions, equityCurveQueryOptions } from './model/queryOptions'
export {
  getStatsSummary,
  getEquityCurve,
  getStatsCycles,
  getHousingBenchmarkComparison,
  getHousingBenchmarkSeries,
  getHousingPriceIndexSeries,
  getEtfPriceSeries,
  getHousingBenchmarkRegions,
} from './api'
export {
  useStatsSummaryQuery,
  useEquityCurveQuery,
  useHousingBenchmarkQuery,
  useHousingBenchmarkSeriesQuery,
  useHousingPriceIndexSeriesQuery,
  useEtfPriceSeriesQuery,
  useHousingBenchmarkRegionsQuery,
  useStatsCyclesQuery,
} from './hooks/useStatsQueries'
export type { EquityCurveParams, RegionSeriesParams, EtfSeriesParams } from './hooks/useStatsQueries'
